name: update-e-stat-data

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run update:data
        env:
          ESTAT_APP_ID: ${{ secrets.ESTAT_APP_ID }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/cities.json
          git commit -m "auto update e-stat data" || exit 0
          git push